groups:
    -   name: node_cpu_seconds-rules
        rules:
            -   record: job:node_cpu_seconds:idle:avg_rate5m
                expr: avg without(cpu) (rate(node_cpu_seconds_total{mode="idle"}[5m]))

            -   alert: JavaWebAppIsDown
                expr: up{job="java-webapp"} == 0
                for: 1m

            -   record: job:webapp_request_latency_seconds:rate1m
                expr: rate(requests_latency_seconds_summary_sum[1m])/rate(requests_latency_seconds_summary_count[1m])

            -   alert: WebAppLatencyAbove5s
                expr: job:webapp_request_latency_seconds:rate1m > 5
                for: 2m
                labels:
                    severity: critical
                annotations:
                    summary: Java web app latency is above 5 seconds
                    description: App latency of instance {{ $labels.intance }} of the job {{ $labels.job }} was > 5s for more than 2min. Current value {{ $value }}.
                    app_link: http://localhost:8080/hello-world/testPrometheusSummary

            -   alert: WebAppLatency2to5s
                expr: 2 < job:webapp_request_latency_seconds:rate1m < 5
                for: 2m
                labels:
                    severity: warning

