useJpa: true
template: Hello, %s!
defaultName: Stranger
server:
    applicationConnectors:
    #    - type: http
    #      port: 8080
        - type: https
    #      port: 8443
          port: 8080
          keyStorePath: /usr/local/bin/client-identity.p12
#          keyStorePath: /Users/thiernoamiroudiallo/src/dropwizart-getting-started/keystore/client-identity.p12
          keyStorePassword: passwordval
    #      keyStoreType: JKS
          keyStoreType: PKCS12
    #      supportedProtocols: [TLSv1, TLSv1.1, TLSv1.2]
          supportedProtocols: [TLSv1.2]
          validateCerts: false
logging:
    level: INFO
    loggers:
        org.hibernate.SQL: DEBUG # Show SQL statements
        org.hibernate.type.descriptor.sql: TRACE # Show the binding parameter values
        org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: INFO # Show internal information of session
        #logging chaching
        org.hibernate.cache: DEBUG
        org.ehcache.cache: DEBUG
        com.thierno.dropwizard.service:
            level: INFO
            additive: false
            appenders:
                -   type: file
                    logFormat: "%d{yyyy.MM.dd;HH:mm:ss.SSS} %-5p [%c] [%t] %m - %n"
                    currentLogFilename: logs/rollingfile.log
                    archivedLogFilenamePattern: logs/rollingfile.log%d{yyyy-MM-dd-HH}.%i.log.gz
                    archivedFileCount: 30
                    totalSizeCap: 500MB
                    maxFileSize: 5MB
    appenders:
        -   type: console
            threshold: ALL
            target: stdout
            logFormat: "%d{yyyy.MM.dd;HH:mm:ss.SSS} %-5p [%c] [%t] %m - %n"
