route:
    receiver: admin

receivers:
    -   name: admin
        email_configs:
            -   to: xx@gmail.com
                from: xx@gmail.com
                smarthost: smtp.gmail.com:587
                auth_username: xx@gmail.com
                auth_identity: xx@gmail.com
                auth_password: xx



                #route:
                #    group_by: [ 'alertname' ]
                #    group_wait: 30s
                #    group_interval: 5m
                #    repeat_interval: 1h
                #    receiver: 'web.hook'
                #receivers:
                #    -   name: 'web.hook'
                #        webhook_configs:
                #            -   url: 'http://127.0.0.1:5001/'
                #inhibit_rules:
                #    -   source_match:
                #            severity: 'critical'
                #        target_match:
            #            severity: 'warning'
#        equal: [ 'alertname', 'dev', 'instance' ]