{
 "title": "Prometheus dashboard",
 "time": { "from": "2022-04-22T23:26:49.921Z", "to": "2022-04-22T23:27:32.121Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Node exporter uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus-node-exporter\"}"
    }
   ]
  },
  {
   "title": "Node exporter uptime duplicate",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"prometheus-node-exporter\"}"
    }
   ]
  },
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Targets health",
   "type": "gauge",
   "description": "instances health",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Java web app", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "App request total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    { "expr": "java_app_requests_total", "legendFormat": "{{ instance }}" }
   ]
  },
  { "title": "Linux machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Node memery percentage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_memory_MemFree_bytes / node_memory_MemTotal_bytes * 100"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 )"
    }
   ]
  },
  {
   "title": "CPU Usage modes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 )",
     "legendFormat": "idle"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"user\"}[1m])) * 100 )",
     "legendFormat": "user"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"system\"}[1m])) * 100 )",
     "legendFormat": "system"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[1m])) * 100 )",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "CPU Usage modes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100 )",
     "legendFormat": "idle"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"user\"}[1m])) * 100 )",
     "legendFormat": "user"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"system\"}[1m])) * 100 )",
     "legendFormat": "system"
    },
    {
     "expr": "(avg by (instance) (irate(node_cpu_seconds_total{mode=\"iowait\"}[1m])) * 100 )",
     "legendFormat": "iowait"
    }
   ]
  },
  {
   "title": "Free disk space percentage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by (instance) (node_filesystem_free_bytes) / sum by(instance) (node_filesystem_size_bytes)) * 100"
    }
   ]
  }
 ]
}