version: "3.8"

services:
    db:
        image: postgres
        container_name: postgres
        ports:
            - 5432:5432
        volumes:
            - ./data/db:/var/lib/postgresql/data
        env_file:
            - database.env
        environment:
            - POSTGRES_DB=dropwizard
